export default {
  extends: ["stylelint-config-standard"],
  overrides: [
    {
      files: ["src/css/index.css"],
      rules: { "at-rule-empty-line-before": null },
    },
    {
      files: [
        "src/css/legacy/**/*.css",
        "src/css/layout/**/*.css",
        "src/css/components/**/*.css",
        "src/css/pages/**/*.css",
        "src/css/overrides/**/*.css",
      ],
      rules: {
        "at-rule-empty-line-before": null,
        "at-rule-no-vendor-prefix": null,
        "color-function-alias-notation": null,
        "color-hex-length": null,
        "comment-empty-line-before": null,
        "comment-whitespace-inside": null,
        "custom-property-empty-line-before": null,
        "declaration-block-no-duplicate-properties": null,
        "declaration-block-no-shorthand-property-overrides": null,
        "declaration-empty-line-before": null,
        "declaration-property-value-keyword-no-deprecated": null,
        "font-family-name-quotes": null,
        "font-family-no-duplicate-names": null,
        "function-name-case": null,
        "keyframe-selector-notation": null,
        "length-zero-no-unit": null,
        "no-duplicate-selectors": null,
        "property-no-deprecated": null,
        "rule-empty-line-before": null,
        "selector-attribute-quotes": null,
        "selector-type-no-unknown": null,
        "shorthand-property-no-redundant-values": null,
      },
    },
  ],
  rules: {
    "alpha-value-notation": null,
    "at-rule-no-unknown": [
      true,
      { ignoreAtRules: ["custom-variant", "source", "theme", "utility"] },
    ],
    "at-rule-prelude-no-invalid": null,
    "color-function-notation": null,
    "custom-property-pattern": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-property-value-no-unknown": null,
    "font-family-no-missing-generic-family-keyword": null,
    "function-url-quotes": null,
    "import-notation": "string",
    "keyframes-name-pattern": null,
    "media-feature-range-notation": null,
    "no-descending-specificity": null,
    "property-no-vendor-prefix": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-not-notation": null,
    "selector-pseudo-element-colon-notation": null,
    "value-keyword-case": null,
    "value-no-vendor-prefix": null,
  },
};
