name: CD

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    uses: Hanserwei/hanlo-theme/.github/workflows/cd.yml@f7f7f561143c8ddbb411a5e5803f6fe50f46ef38
    with:
      tag: ${{ github.event.release.tag_name }}
